### PR TITLE
Add --if-exists option to topic delete, describe, and alter subcommands and fix --help option functionality

### LINKED ISSUE #83: Admin-client: add `if-exists` option to delete a topic
As part of the development of the Kroxylicious system tests, we have found the need of having an option like [kafka](https://github.com/apache/kafka/blob/5c929874b88b3b96f650de0f733d93d42ac535a4/tools/src/main/java/org/apache/kafka/tools/TopicCommand.java#L796) already have to delete a topic only if it exists and not report and error if don't.

I guess it should be straight forward to add this `--if-exists` option already supported and nothing else need to be done.

### PR DESCRIPTION
**Pull request by im-konge**
This PR adds possibility to specify, if the topics that are not present in Kafka during operations delete, describe, and alter, should or should not be ignored - by specifying the `--if-exists` flag.

Also, this PR fixes the `--help` option not working in most of the sub-commands.

Closes #83

### CODE REVIEW

File: admin/src/main/java/io/strimzi/arguments/topic/IfExistsTopicCommand.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+     * Method that checks that all expected Kafka topics are present in Kafka, before particular operation is done.
+     * In case that the {@link #ifExists} is true, the topic (in case that it doesn't exist in Kafka) is removed from the List.
+     * Otherwise, the exception is thrown.
+     *
+     * @param topicsInKafka     topics present in Kafka
+     * @param expectedTopics    list of expected topics that should be in Kafka
+     *
+     * @return  list of topics that should be managed
+     */
+    List<String> checkIfTopicExists(List<String> topicsInKafka, List<String> expectedTopics) {
```
Comment (henryZrncik) [inline admin/src/main/java/io/strimzi/arguments/topic/IfExistsTopicCommand.java:32]: maybe the name is a bit misleading as we are checking several topics ?  Maybe rather 
`checkIfTopicsExist` or `verifyTopicsExistence`

**Review by see-quick — APPROVED** [review]
Good job! 👍

**Review by henryZrncik — APPROVED** [review]
Thanks! Good job, just one nit  👍
